### ISSUE TITLE
I would like to browse existing emoji without having to search

### ISSUE THREAD

**Issue by jlsuttles** [willmanduffy/mojician#1]
Omg yay congrats @willmanduffy! ✨ I am so excited to use this. Thank you for making it ❤️ 

So far I have searched for avocado, obvi. And I found it and it is perfect! But I'm curious what else is out there and I'd really like to be able to just scroll through what's available to get my creative juices flowing on what emoji I can use to annoy/inspire my slack mates.

PS... FIRST!!!

**Comment by willmanduffy** [comment]
Totally agree! I pushed out the default page last night to be https://www.mojician.com/emojis which let's you scroll through the latest emoji.

I have 2 plans for the immediate future:

1.) This week: When clicking the Mojician logo in the top left it'll clear all query params so you don't need to manually delete your last search term.

2.) Soon™: Adding filters to this page to sort by upload date, popularity, name, etc. 

Thanks for your kind words!

**Comment by jlsuttles** [comment]
Ooookay I _just_ notice that if I click on the logo at the top it takes me to https://www.mojician.com/emojis which is exactly what I wanted 🙃

**Comment by jlsuttles** [comment]
Thanks Will!
