### ISSUE TITLE
Compliment: Despite all of the bugs I am filing, this site is great and cool, good job!!

### ISSUE THREAD

**Issue by mknadler** [willmanduffy/mojician#11]
:100: :rocket: :heart: :heart_eyes_cat: :tada: :balloon: :birthday: :gift: :100: :rocket: :heart: :heart_eyes_cat: :tada: :balloon: :birthday: :gift: :100: :rocket: :heart: :heart_eyes_cat: :tada: :balloon: :birthday: :gift: :100: :rocket: :heart: :heart_eyes_cat: :tada: :balloon: :birthday: :gift: :100: :rocket: :heart: :heart_eyes_cat: :tada: :balloon: :birthday: :gift: :100: :rocket: :heart: :heart_eyes_cat: :tada: :balloon: :birthday: :gift: :100: :rocket: :heart: :heart_eyes_cat: :tada: :balloon: :birthday: :gift: :100: :rocket: :heart: :heart_eyes_cat: :tada: :balloon: :birthday: :gift: :100: :rocket: :heart: :heart_eyes_cat: :tada: :balloon: :birthday: :gift: :100: :rocket: :heart: :heart_eyes_cat: :tada: :balloon: :birthday: :gift: :100: :rocket: :heart: :heart_eyes_cat: :tada: :balloon: :birthday: :gift: :100: :rocket: :heart: :heart_eyes_cat: :tada: :balloon: :birthday: :gift: :100: :rocket: :heart: :heart_eyes_cat: :tada: :balloon: :birthday: :gift: :100: :rocket: :heart: :heart_eyes_cat: :tada: :balloon: :birthday: :gift: :100: :rocket: :heart: :heart_eyes_cat: :tada: :balloon: :birthday: :gift: :100: :rocket: :heart: :heart_eyes_cat: :tada: :balloon: :birthday: :gift: :100: :rocket: :heart: :heart_eyes_cat: :tada: :balloon: :birthday: :gift: :tada: :balloon: :birthday: :gift:

**Comment by willmanduffy** [comment]
Thank you so much for the bug reports and kind words! As you can see I didn't really test this out in other browsers as much as I should have. Was just trying to get something out the door :) I'll be taking a look into all of them!

<3
