### ISSUE TITLE
Bug: When window size is small, pagination items stack, lack vertical gap

### ISSUE THREAD

**Issue by mknadler** [willmanduffy/mojician#13]
<img width="261" alt="stackedpagination" src="https://cloud.githubusercontent.com/assets/3596891/17644891/941deb34-6162-11e6-9541-3b8d02cf40f7.PNG">

(another option here might be to restrict the number of visible pagination buttons so that they all fit on one line?)

**Comment by willmanduffy** [comment]
Just deployed and added a vertical gap! I couldn't figure out how to restrict the number of visible buttons with the addon I'm using for pagination and I don't think it supports it. Went for the simple solution.

Thanks for the report!
