### ISSUE TITLE
Bug: Unable to register (You need to pick a username!)

### ISSUE THREAD

**Issue by mattcdowning** [willmanduffy/mojician#14]
When trying to register on El Capitan 10.11.6 in Chrome (Version 52.0.2743.116 (64-bit)) / Safari (Version 9.1.2 (11601.7.7)) it alerts me to enter a username even though one is present. Console reads "Failed to load resource: the server responded with a status of 422 ()" for https://api.mojician.com/users. Hope that helps :)

Thanks for this fun project btw!

**Comment by willmanduffy** [comment]
Whoops, my bad. I redesigned all my forms last night and had a typo and my tests didn't catch it. (Reminder for me to improve those). I just pushed out what's hopefully a fix!

Let me know how it goes and thanks so much for reporting this!

**Comment by mattcdowning** [comment]
That did it!
