### ISSUE TITLE
Bug: emoji has odd aspect ratio when uploading

### ISSUE THREAD

**Issue by nelsonpecora** [willmanduffy/mojician#15]
When uploading emoji, the preview has an odd aspect ratio (different than the uploaded file). After upload it looks correct, though.

![mikeaschneider_2016-aug-25](https://cloud.githubusercontent.com/assets/447522/17978847/f09b6488-6ac5-11e6-8416-561eabf9a271.jpg)

![screen shot 2016-08-25 at 1 14 10 pm](https://cloud.githubusercontent.com/assets/447522/17978860/f62f07ba-6ac5-11e6-983b-c58766cf5f78.png)

**Comment by willmanduffy** [comment]
Yup! I recently switched over to flexbox on all the emoji locations and forgot that upload used the same code. This is next on my list, but thanks for raising it! I'll prioritize it even more now :)

**Comment by willmanduffy** [comment]
This should be all sorted out now in the latest release! Let me know if there's issues.
