### ISSUE TITLE
lightbox doesn't go away for emojis not in my collection

### ISSUE THREAD

**Issue by sheley** [willmanduffy/mojician#2]
Ohhh boy I was so excited when I got my invite today 💃 (i still am!)

I noticed that when I click on an emoji so that the lightbox overlay thing appears, I can't make it go away by clicking outside the box (in the red area) as I can for emojis that ARE in my collection.

<img width="993" alt="screen shot 2016-08-05 at 17 12 26" src="https://cloud.githubusercontent.com/assets/3749305/17441098/d3cd6270-5b2f-11e6-8175-41527514df94.png">

so in the example above, :parrot: is not in my collection and I'm stuck looking at it like this, because I decided I don't need it in my collection! 

Also not sure if it needs a separate issue, but when that does work (clicking outside the box to go back to the regular search view), it only works on the red areas above and below the white box, but not to the left or the right.

lemme know if i'm being unclear or you need more info!

**Comment by willmanduffy** [comment]
Interesting. I'm having a bit of trouble re-creating this, although I don't doubt what you're hitting at all. To be honest this emoji overlay is one of the areas of the site that still needs a lot of development work!

Quick question, what browser / OS are you hitting this in? I'll try to re-create. Also are you clicking on the emoji or opening them in a new tab?

**Comment by sheley** [comment]
i'm on osx using Chrome `Version 51.0.2704.103 (64-bit)`. I'm clicking on them, not opening a new tab

**Comment by willmanduffy** [comment]
Whoops. Didn't mean to close this, I referenced it in a commit I had. I just pushed some fixes out that might make this a little bit better hopefully! Let me know if that help :D

**Comment by sheley** [comment]
haha no problem. Everything looks fixed! the red area around each side of the box (left and right also) all make the box disappear as expected for both emojis in my collections and not in my collections! ⭐
