### ISSUE TITLE
Request: Some visual indicator of success when item dragged into collection

### ISSUE THREAD

**Issue by mknadler** [willmanduffy/mojician#6]
This would help with situations like #5, but would also be nice in general, I think.

Currently, when you drag an emoji into a collection, there's no way to know whether or not it was actually added without opening the collection. Given that this would involve navigating away from the main screen, it might be nice to have something like a :white_check_mark: , a color change, or an item count appended to the collection name incrementing.

**Comment by willmanduffy** [comment]
Yup, this one's on my shortlist. Thanks for creating the issue I'm prioritizing UI improvements that people suggest so I'll bump this one up!

**Comment by willmanduffy** [comment]
![untitled](https://cloud.githubusercontent.com/assets/782252/17838456/204823ec-679c-11e6-83a9-3b7e26695819.gif)

Now up on production!
